<a href="https://colab.research.google.com/github/Rakeshsingu/import-and-export-of-an-array/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

list vs numpy time taken

In [6]:
from time import process_time

Time taken by a list

In [7]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0036535070000001113


In [8]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 #np_array = np_array + 5 

end_time = process_time()

print(end_time - start_time)

0.0015721399999999441


creating a 1 dimensional numpy array

In [9]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [10]:
a.shape

(5,)

creating a 2d numpy array

In [11]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


initial place holder in numpy arrays

In [13]:
#create a numpy array of zeros 
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
#array of a particular value
z = np.full((5,4),5) 
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
#create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [21]:
#create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.23128131 0.33887911 0.61971523 0.48046212]
 [0.29185562 0.83310806 0.58094871 0.71803142]
 [0.71136728 0.93622039 0.41002695 0.01751228]]


In [22]:
#random integer values array within a specific range 
c = np.random.randint(10,100,(3,5))
print(c)

[[18 18 26 30 33]
 [50 86 38 18 79]
 [39 69 65 64 23]]


In [23]:
#array of evenly spaced values ---specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [24]:
#array of evenly spaced values ---specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [26]:
#convert a list to a numpy 
list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


Analysing a numpy array

In [29]:
c = np.random.randint(10,90,(5,5))
print(c)

[[61 73 28 67 54]
 [10 29 89 60 48]
 [22 24 20 21 89]
 [26 23 16 61 21]
 [40 71 13 30 26]]


In [30]:
#array dimension
print(c.shape)


(5, 5)


In [31]:
#number of dimensions 
print(c.ndim)

2


In [32]:
#number of elements in an array
print(c.size)

25


In [33]:
#checking the data type of vlaues in the array 
print(c.dtype)

int64


Mathematical operation on a np array 

In [34]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2) #concatenate two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [35]:
a = np.random.randint(0,10,(3,3)) 
b = np.random.randint(10,20,(3,3))

In [36]:
print(a)
print(b)

[[3 2 4]
 [9 2 3]
 [7 2 8]]
[[10 16 12]
 [12 17 10]
 [12 13 11]]


In [37]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)


[[13 18 16]
 [21 19 13]
 [19 15 19]]
[[ -7 -14  -8]
 [ -3 -15  -7]
 [ -5 -11  -3]]
[[ 30  32  48]
 [108  34  30]
 [ 84  26  88]]
[[0.3        0.125      0.33333333]
 [0.75       0.11764706 0.3       ]
 [0.58333333 0.15384615 0.72727273]]


In [38]:
print(np.add(a,b))

[[13 18 16]
 [21 19 13]
 [19 15 19]]


In [41]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ -7 -14  -8]
 [ -3 -15  -7]
 [ -5 -11  -3]]
[[ 30  32  48]
 [108  34  30]
 [ 84  26  88]]
[[0.3        0.125      0.33333333]
 [0.75       0.11764706 0.3       ]
 [0.58333333 0.15384615 0.72727273]]


Array Manipulation

In [43]:
array = np.random.randint(0,10,(2,3))  
print(array)
print(array.shape)

[[8 9 9]
 [8 5 6]]
(2, 3)


In [45]:
#transpose 
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[8 8]
 [9 5]
 [9 6]]
(3, 2)


In [46]:
array = np.random.randint(0,10,(2,3))  
print(array)
print(array.shape)

[[9 8 8]
 [1 7 3]]
(2, 3)


In [47]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 1]
 [8 7]
 [8 3]]
(3, 2)


In [48]:
#reshaping an array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[2 1 8]
 [2 5 1]]
(2, 3)


In [53]:
b = a.reshape(3,2)
print(b)

[[2 1]
 [8 2]
 [5 1]]
